# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    # 💡 AJOUTE CECI : On dit au client HTTP de ne pas bloquer les certificats locaux
    http_client:
        default_options:
            verify_peer: false
            verify_host: false
            timeout: 300

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
