framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                # La magie opère ici :
                failure_transport: failed

            failed: 'doctrine://default?queue_name=failed'
        routing:
            # 💡 On dit à Symfony : "Tous les GenerateArticleMessage vont dans l'async"
            App\Message\GenerateArticleMessage: async
