name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  containers-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose services
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 10

      # 🚀 On ajoute "--user root" pour écraser la restriction dans la CI
      - name: Install Composer Dependencies
        run: docker compose run --user root --rm webgateway composer install --prefer-dist --no-progress --no-interaction

      # 🎯 Même chose ici pour que les linter et tests s'exécutent sans blocage
      - name: Run Quality and Security Tests
        run: docker compose run --user root --rm webgateway composer test

      - name: Print container logs on failure
        if: failure()
        run: docker compose logs