name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  containers-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Docker Compose services
        run: docker compose up -d --build

      - name: Wait for services
        run: sleep 10

      # 🚀 Correction ici : on passe de "exec" à "run --rm"
      - name: Run Quality and Security Tests
        run: docker compose run --rm webgateway composer test

      # 🔍 En cas d'échec, cette étape affiche les logs Docker pour débugger instantanément
      - name: Print container logs on failure
        if: failure()
        run: docker compose logs